name: GITRU-T1147 (1.0) [CI/CD] Блокирование слияния пулл реквеста при неуспешном прогоне задания (джоба)
on:
  push:
jobs:
  Job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Job 1 step completed"
  
  Job2:
    needs: Job3
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Job 2 step completed"
  
  Job3:
    needs: Job1
    name: Job 3
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Job 3 step completed"
